### ISSUE TITLE
Spaces are being replaced with "%20" strings

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/grunt-electron-installer#105]
As per this issue here raised on my repository.  https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/200

The short of it is, for whatever reason the Russian version of Windows 7 (not sure about other versions) doesn't like the `%` sign in the file name when launching through `Update.exe`.  The problem here is that I didn't put those `%` signs there, they used to be spaces and this module run some kind of escape over the filename.

Can this behaviour be changed so that these % signs do not appear?

**Comment by paulcbetts** [comment]
This is a bug in Squirrel.Windows that I need to fix

**Comment by MarshallOfSound** [comment]
@paulcbetts Ah, I wasn't sure which repo was responsible :+1: 

Is there any way to keep the productName with spaces but have the exe name with spaces?

**Comment by Namynnuz** [comment]
@MarshallOfSound In fact, it's not really a multi-platform way to make spaces in the names (also as some unicode symbols, pretty anything but [a-zA-Z0-9]). All of that %20 instead of space symbol and other percent-encoding stuff is really common in URIs, so it's kinda mandatory to use [a-zA-Z0-9] symbols only (for any multi-platform releases).

**Comment by paulcbetts** [comment]
> All of that %20 instead of space symbol and other percent-encoding stuff is really common in URIs, so it's kinda mandatory to use [a-zA-Z0-9] symbols only (for any multi-platform releases).

No, this is just a stupid bug in Squirrel.Windows that I haven't fixed

**Comment by havenchyk** [comment]
@paulcbetts will it be handled as a part of https://github.com/Squirrel/Squirrel.Windows/issues/603, https://github.com/Squirrel/Squirrel.Windows/issues/544 and https://github.com/Squirrel/Squirrel.Windows/issues/414?

**Comment by havenchyk** [comment]
Fixed in squirrel.windows.
