### ISSUE TITLE
Warning: Cannot read property 'description' of null  Use --force to continue.

### ISSUE THREAD

**Issue by GeeshangXu** [electron/grunt-electron-installer#112]
I am using Grunt V1.0.1 and grunt-electron-installer V2.0.0, the build is failed with this Warning, and when add --force to grunt command ,there is nothing generated except "update.exe". Does it could be a bug?

**Comment by havenchyk** [comment]
it's a known issue.  Please, check, is it the same? https://github.com/electron/windows-installer/issues/41

**Comment by GeeshangXu** [comment]
Maybe, but  [https://github.com/electron/windows-installer/issues/41]( electron/windows-installer#41) didn't solve the problem. And the strange thing is the problem do not show anymore when i install Grunt and grunt-windows-installer again, replace with infinite waiting '"Running "create-windows-installer:ia32" (create-windows-installer) task", the release are full of bugs i think, maybe i just go to use electron-packager or  electron-builder.

**Comment by GeeshangXu** [comment]
Seems this project is base on windows-installer, but electron/windows-installer#41 is still open open right now, not solved.

**Comment by havenchyk** [comment]
@GeeshangXu yes, but 2.2.0 already released, probably. Could you please re-install grunt-electron-installer and check once again?

**Comment by GeeshangXu** [comment]
@havenchyk  Yes, this problem sovled by replace the old electron-winstaller V2.0.5 in grunt-electron-installer's node_modules with the latest version V2.2.0, thank you!  But the the latest version 2.0.0 of grunt-electron-installer is still depend on the old electron-winstaller 2.0.5, so it need to be updated to fix the issue.

**Comment by havenchyk** [comment]
@GeeshangXu glad you solved your issue. Well, I haven't rights to merge pr's, maybe @kevinsawicki could provide them? I'll be glad to update to the latest version.

**Comment by havenchyk** [comment]
@GeeshangXu let's wait for new version, fix is already merged.

**Comment by GeeshangXu** [comment]
Good!
