### ISSUE TITLE
Can't change default atom-shell metadata icon

### ISSUE THREAD

**Issue by bostondv** [electron/grunt-electron-installer#16]
When installing the generated setup file, an atom-shell .ico file is placed in `./AppData/Local/myapp/app.ico`. This icon is displayed in add remove programs (and maybe other places?).

I can't find any way to change this.

Browsing the source I found the undocumented `iconUrl` option, it defaults to the atom-shell icon. However, this option in the gruntfile has no result on the installed .ico file. I've tried absolute, relative, and public web url values with no luck.

```
'create-windows-installer': {
      appDirectory: 'dist/windows/build',
      outputDirectory: 'dist/windows/installer',
      iconUrl: '../resources/windows/myapp.ico',
      setupIcon: '../resources/windows/myapp.ico',
      certificateFile: '../resources/windows/cert.p12',
      certificatePassword: 'xxxxxxxx',
      loadingGif: '../resources/windows/installer.gif'
}
```

**Comment by rwhitmire** [comment]
+1

anyone have any info on this? would be glad to submit a pull request if needed.

**Comment by rwhitmire** [comment]
Usually when i comment on an issue, it takes me around 5 minutes to figure it out.

@bostondv - try setting `iconUrl` to an actual URL. I plopped my icon in the public folder in Dropbox and that worked for me.

**Comment by bostondv** [comment]
It did end up working for me using a public web URL. But would be handy if this supported using a local icon file.

**Comment by pracucci** [comment]
If `iconUrl` is an *https* url  it doesn't work to me (Windows 8.1, the SSL certificate is valid). If I switch to an *http* url it works.

**Comment by gbmhunter** [comment]
+1, can't get the icon to change.

**Comment by havenchyk** [comment]
IconUrl should an url to your icon. It's limitation of nuget, can't be fixed.
