### ISSUE TITLE
remoteReleases option appears to add extra '/' in requests

### ISSUE THREAD

**Issue by marwanhilmi** [electron/grunt-electron-installer#32]
With a configuration like this:
```
  opts =
    'create-windows-installer':
      appDirectory: './app'
      outputDirectory: './releases'
      remoteReleases: 'http://127.0.0.1:3000'
```
You can see requests for the RELEASES file and corresponding packages coming with an extra '/'. Example logs from my Express server:
```
GET //RELEASES 200 1.470 ms - -
GET //RELEASES 200 1.128 ms - -
```
So note the full URL being requested is ***http://127.0.0.1:3000//RELEASES***.
I can fudge it this Express server but if I change remoteReleases to an S3 bucket, it'll obviously not work and return 404 when requesting the RELEASES file.

This appears on current version 0.33.

**Comment by marwanhilmi** [comment]
It appears to work normally if the remoteReleases has an additional element in the path, for example:

```
 opts =
    'create-windows-installer':
      appDirectory: './app'
      outputDirectory: './releases'
      remoteReleases: 'http://127.0.0.1:3000/foo'
```
Will work correctly:
```
GET /foo/RELEASES 200 1.070 ms - -
```

I was then able to get my S3 remote bucket working by putting everything a subfolder.
It appears the issue may lie in Squirrel itself as it doesn't appear the code here modified the URL.

**Comment by paulcbetts** [comment]
Can you file this bug on https://github.com/squirrel/squirrel.windows?

**Comment by havenchyk** [comment]
Please, create issue on squirrel.windows, if it's still a problem.
