### ISSUE TITLE
Command path generated is too long, can't create installer

### ISSUE THREAD

**Issue by techninja** [electron/grunt-electron-installer#39]
I'm not sure how everyone else has been able to get theirs working, but I've been completely unable to get this going. Using Windows 7, x64, MSVS 2013 Express Desktop. When running `grunt create-windows-installer`, I get the following when building the installer for my robopaint project:
```
>> The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
Warning: Command failed: C:\rpb\node_modules\grunt-electron-installer\vendor\nuget.exe pack C:\Users\TECHNI~1\AppData\Local\Temp\squirrel-installer-115620-7836-vbwmay\robopaint.nuspec -BasePath C:\rpb\out\Robopaint-win32
-x64 -OutputDirectory C:\Users\TECHNI~1\AppData\Local\Temp\squirrel-installer-115620-7836-vbwmay -NoDefaultExcludes
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
 Use --force to continue.
```
I suspec that `AppData` as the temp location may be to blame for path character bloat, but wow the mere fact that there's a limit sure is annoying. I did find this:

>Maximum Path Length Limitation
>
>In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters. A local path is structured in the following order: drive letter, colon, backslash, name components separated by backslashes, and a terminating null character. For example, the maximum path on drive D is "D:\some 256-character path string<NUL>" where "<NUL>" represents the invisible terminating null character for the current system codepage. (The characters < > are used here for visual clarity and cannot be part of a valid path string.)
Note  File I/O functions in the Windows API convert "/" to "\" as part of converting the name to an NT-style name, except when using the "\\?\" prefix as detailed in the following sections.
>
>The Windows API has many functions that also have Unicode versions to permit an extended-length path for a maximum total path length of 32,767 characters. This type of path is composed of components separated by backslashes, each up to the value returned in the lpMaximumComponentLength parameter of the GetVolumeInformation function (this value is commonly 255 characters). To specify an extended-length path, use the "\\?\" prefix. For example, "\\?\D:\very long path".
>Note  The maximum path of 32,767 characters is approximate, because the "\\?\" prefix may be expanded to a longer string by the system at run time, and this expansion applies to the total length.
>
>The "\\?\" prefix can also be used with paths constructed according to the universal naming convention (UNC). To specify such a path using UNC, use the "\\?\UNC\" prefix. For example, "\\?\UNC\server\share", where "server" is the name of the computer and "share" is the name of the shared folder. These prefixes are not used as part of the path itself. They indicate that the path should be passed to the system with minimal modification, which means that you cannot use forward slashes to represent path separators, or a period to represent the current directory, or double dots to represent the parent directory. Because you cannot use the "\\?\" prefix with a relative path, relative paths are always limited to a total of MAX_PATH characters.

Makes me think if we initiate this command with `\\?\` this wouldn't be an issue? Hmm.

I've tried setting the global npm `tmp` via `npm config set tmp "C:\tmp"`, but it didn't seem to actually change it when the script runs. Any ideas?

**Comment by techninja** [comment]
Ran this on a completely different Windows 7 x64 machine, took a lot longer, and apart from a strange issue with chromium pickle which was fixed by copying the node_modules from the other machine, seemed to work up till this:
```
>> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
>>    at System.IO.PathHelper.GetFullPathName()
>>    at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
>>    at System.IO.Path.GetFullPathInternal(String path)
>>    at System.IO.Path.GetFullPath(String path)
>>    at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
>>    at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restor
eDateTime, Boolean isStreamOwner)
>>    at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restor
eDateTime)
>>    at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String targetDirectory, String fileFilter)
>>    at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
>>    at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon)
>>    at Squirrel.Update.Program.executeCommandLine(String[] args)
>>    at Squirrel.Update.Program.main(String[] args)
>>    at Squirrel.Update.Program.Main(String[] args)
Warning: Command failed: C:\rpb\node_modules\grunt-electron-installer\vendor\Update.com --releasify C:\Users\TECHNI~1\AppData\Local\Temp\squirrel-installer-115621-4376-1qbzlhr\robopaint.0.9.6.nupkg --releaseDir C:\rpb\ou
t\winstall --loadingGif C:\rpb\resources\win\install_anim.gif
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDa
teTime, Boolean isStreamOwner)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDa
teTime)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String targetDirectory, String fileFilter)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
 Use --force to continue.

Aborted due to warnings.
```

Different, yet the same. I'm going to attempt to run this either in a clean install virtual machine, or some other system that doesn't have anything possibly questionable going on. Am I right to assume that usually these windows builds are done from a clean virtual windows box?

**Comment by techninja** [comment]
To Reproduce: 32 bit Win 7 build Virtualbox VM (via [modern.ie](http://dev.modern.ie/tools/vms/)):
- Install MS VisualStudio express 2013 desktop (wait approx 2 hours)
- Install git (_with_ unix command line tools option during install, very handy)
- Install io.js (2.4.0)
- Install python 2.7.x
- From cmd: `npm install -g grunt-cli node-gyp`
- Clone repo, `npm install`, copy pre-built resources for installer packaging
- run `grunt create-windows-installer` (Wait very patiently)

Got the same error as above.

**Comment by techninja** [comment]
Managed to change the `%temp%' path variable and it helped, but it didn't help _enough_. I have a feeling that we're not actually looking at the path with the issue. Maybe need to try with NPMv3? :P

```
Warning: Command failed: C:\rpb\node_modules\grunt-electron-installer\vendor\Upd
ate.com --releasify C:\tmp\squirrel-installer-115621-704-5jdv4d\robopaint.0.9.6.
nupkg --releaseDir C:\rpb\out\winstall --loadingGif C:\rpb\resources\win\install
_anim.gif
System.IO.PathTooLongException: The specified path, file name, or both are too l
ong. The fully qualified file name must be less than 260 characters, and the dir
ectory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPath
Length, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String
targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate,
String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isSt
reamOwner)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String
targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate,
String fileFilter, String directoryFilter, Boolean restoreDateTime)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String
targetDirectory, String fileFilter)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String pac
kagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String
 packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts,
String baseUrl, String setupIcon)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
```

**Comment by paulcbetts** [comment]
Try running `npm dedupe` and making sure that `NODE_ENV` is set to `production`

**Comment by techninja** [comment]
Set the `NODE_ENV` and checked it with `echo %NODE_ENV%`, then ran dedupe, then `grunt create-windows-installer`, no change, same error as the initial comment. Here's the output from dedupe:
```
npm WARN unavoidable conflict rimraf { 'C:\rpb\node_modules\fs-plus\node_modules\rimraf': '2.2.8',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt\node_modules\rimraf': '2.2.8',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\rimraf': '2.4.2',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron-installer\node_modules\temp\node_modules\rimraf': '2.2.8' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict through2 { 'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\electron-download\node_modules\nugget\node_modules\progress-stream\node_modules\through2': '0.2.3',

npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\extract-zip\node_modules\through2': '0.6.3' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict underscore.string { 'C:\rpb\node_modules\grunt\node_modules\grunt-legacy-log\node_modules\underscore.string': '2.3.3',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt\node_modules\js-yaml\node_modules\argparse\node_modules\underscore.string': '2.4.0',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt\node_modules\underscore.string': '2.2.1' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict mkdirp { 'C:\rpb\node_modules\fs-plus\node_modules\mkdirp': '0.3.5',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\extract-zip\node_modules\mkdirp': '0.5.0',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\mkdirp': '0.5.1' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict minimist { 'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\minimist': '1.1.1',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\extract-zip\node_modules\minimist': '0.1.0' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict debug { 'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\electron-download\node_modules\nugget\node_modules\debug': '2.2.0',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\extract-zip\node_modules\debug': '0.7.4' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict underscore { 'C:\rpb\node_modules\fs-plus\node_modules\underscore-plus\node_modules\underscore': '1.6.0',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt\node_modules\js-yaml\node_modules\argparse\node_modules\underscore': '1.7.0',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron-installer\node_modules\underscore': '1.8.3' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict asar { 'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\asar': '0.6.1',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron-installer\node_modules\asar': '0.2.2' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict lodash { 'C:\rpb\node_modules\grunt\node_modules\grunt-legacy-log\node_modules\lodash': '2.4.2',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt\node_modules\lodash': '0.9.2' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict async { 'C:\rpb\node_modules\fs-plus\node_modules\async': '0.2.10',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt\node_modules\async': '0.1.22',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\electron-download\node_modules\nugget\node_modules\request\node_modules\form-data\node_modules\async': '1.4.
0',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt-electron\node_modules\electron-packager\node_modules\extract-zip\node_modules\async': '0.9.0' }
npm WARN unavoidable conflict Not de-duplicating
ansi-regex@2.0.0 node_modules\grunt-electron\node_modules\electron-packager\node_modules\electron-download\node_modules\nugget\node_modules\request\node_modules\har-validator\node_modules\chalk\node_modules\ansi-regex
nopt@1.0.10 node_modules\nopt
└── abbrev@1.0.7
readable-stream@2.0.2 node_modules\grunt-electron\node_modules\electron-packager\node_modules\readable-stream
├── process-nextick-args@1.0.2
├── isarray@0.0.1
├── inherits@2.0.1
├── util-deprecate@1.0.1
├── string_decoder@0.10.31
└── core-util-is@1.0.1
findup-sync@0.1.3 node_modules\findup-sync
├── lodash@2.4.2
└── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
npm WARN unavoidable conflict glob { 'C:\rpb\node_modules\findup-sync\node_modules\glob': '3.2.11',
npm WARN unavoidable conflict   'C:\rpb\node_modules\grunt\node_modules\glob': '3.1.21' }
npm WARN unavoidable conflict Not de-duplicating
```
What a sticky wicket NPM's got itself into :P

**Comment by techninja** [comment]
It looks like what's going on here is the path is not shown, but is triggered from the app being run on the node application itself. The "fix" as mentioned in the basic duplicate of my ticket ( #34 ), is to package the app as an asar... which I've been intending to to avoid, and is possibly why I've been having issues (other than deep npm dirs).

I will do some tweaking on my apps end and report back.

**Comment by techninja** [comment]
I've fully confirmed that the issue at hand here are the extensive nested paths within the app, not within the actual thing doing the building. Hence why ASAR packaging is a clear fix, and likely why few others seem to encounter the problem directly.

My personal fix was to use the downright frightening module, [`flatten-packages`](https://www.npmjs.com/package/flatten-packages), which does away with all version separation and puts every module used anywhere on the same folder. As it says on the tin, this can totally break things. Luckily it works for me (I _think_), but I hazard to say that if a project can't use ASAR packaging _**and**_ has this problem, it's not a healthy thing to suggest flatten as the only way out.

@paulcbetts I'll leave this for you close at your discretion, though we likely might need a better long term answer.

**Comment by suhaibmalik** [comment]
Same problem as @techninja 

Was struggling with this problem for hours upon hours yesterday. Same exact issue. I went as far as having the entire command land shortened to below 260 chars and still no avail.

**Comment by paulcbetts** [comment]
> Luckily it works for me (I think), but I hazard to say that if a project can't use ASAR packaging and has this problem, it's not a healthy thing to suggest flatten as the only way out.

What are the scenarios in which you can't use ASAR? They should all work, though you have to use `unpacked` sometimes and its documentation is pretty sparse

**Comment by techninja** [comment]
Apart from complexities with writing config files and downloads to "internal" locations, I personally prefer open packaging for my app because I'd like to keep the files and folder resources as open as possible, so advanced users can dive right in and edit things as needed (and as I've been called upon to do multiple times).

As I've said, I'm not totally sure that there even is a universal solution to the issue (apart from NPM 3's plan), especially considering that if there are problems creating the installer, it seems possible that even copying the files/folders into even longer paths are going to cause even more problems down the line.

One thing is clear though, you can likely close this issue as we know the actual problem lies with the application being packaged (not this project itself). If possible, the script should catch the error and give a clear explanation of windows OS limitations and possible solutions. Might even be able to do a pre-scan of the input dir structure and quit before even trying.

**Comment by paulcbetts** [comment]
> Apart from complexities with writing config files and downloads to "internal" locations

You can't do this anyways, because on Mac you'll break the app's signature, and on Linux, you're installed to `/usr/share` where you cannot write files

**Comment by techninja** [comment]
I have yet to test with a codesigned app, or with a proper linux install, so that would explain that. :/

**Comment by sergiovilar** [comment]
I have the same issue, how to solve?

**Comment by kneumei** [comment]
@sergiovilar when you run electron-packager, use `--asar=true`

**Comment by sergiovilar** [comment]
@kneumei oh, I'll give a try. Thank you!

**Comment by sergiovilar** [comment]
@kneumei solved the problem, thanks!

**Comment by Akamaozu** [comment]
@paulcbetts i ran into a scenario where i can't use asar.

Im using [pdf_page_count](https://www.npmjs.com/package/pdf_page_count) and it absolutely refuses to work with asar. It bundles up, but it throws an error every time the package is being used. 

Ive tried a couple other npm packages but it seems like I'm stuck using `pdf_page_count` and it doesn't work in asar and electron installer won't work if it isn't an asar.

**Comment by paulcbetts** [comment]
> Im using pdf_page_count and it absolutely refuses to work with asar. It bundles up, but it throws an error every time the package is being used.

So, this is where you need to use the "Unpack" feature of ASAR - https://github.com/atom/asar/pull/25, this will unpack certain file types to just a folder, and ASAR will redirect it for you behind the scenes

**Comment by gamicklisafisher** [comment]
You should check out ‘Long Path Tool’ it will help you fix the issues.
I had faced similar issue and this tool helped me to resolve this issue.

**Comment by Akamaozu** [comment]
You can upgrade to npm3 ... the new flat dependency tree will solve this issue automatically :)

**Comment by havenchyk** [comment]
Use `npm3` or `npm dedupe` with `npm2`. I believe it's the only way to fix this issue.
