### ISSUE TITLE
option for setting minimum install duration?

### ISSUE THREAD

**Issue by grofit** [electron/grunt-electron-installer#46]
I was wondering if it would be plausible to add an option for minimum install time, like for example if you wanted the install to take at minimum 20 seconds to complete.

In my scenario I have a loading gif that I would like to finish its animation run before it is closed, not end of the world if its not a quick thing to do.

**Comment by havenchyk** [comment]
I think you can use gif animation for that purposes. If you have an idea, how to implement it or just would like this feature to be added, please, create an issue on https://github.com/electron/windows-installer
