### ISSUE TITLE
Description option is required

### ISSUE THREAD

**Issue by Partysun** [electron/grunt-electron-installer#48]
I have error "Description is required." After I added descriptions in package.json, everything is ok.
It's not very important, but...

**Comment by smilejp** [comment]
@Partysun 
did you succeeded build?
I have same error "Description is required". 
so I added description in package.json,  
but another error occured. "File not found : LICENSE"
what is LICENSE file? how to create it?

i don't know. how to fix it.
could you help me?

here is my gruntfile.js and package.json
gruntfile.js
```javascript
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    'create-windows-installer': {
      x64: {
        appDirectory: '../electron/',
        outputDirectory: '/output',
        authors: 'My App Inc.',
        exe: 'myapp.exe'
      }
    }
  });

  grunt.loadNpmTasks('grunt-electron-installer');

  // Default task(s).
  grunt.registerTask('default', ['create-windows-installer']);
};
```

package.json
```javascript
{
  "name": "test",
  "version": "0.1.0",
  "description": "An example module to illustrate the usage of a package.json",
  "main": "main.js"
}
```

**Comment by havenchyk** [comment]
@Partysun what can you suggest to make things more understandable?

**Comment by havenchyk** [comment]
It's required. Can be closed.
