### ISSUE TITLE
iconUrl should accept local files

### ISSUE THREAD

**Issue by romaincointepas** [electron/grunt-electron-installer#73]
`setupIcon` does accept a local .ico file, is there any reason why it can't be the same for `iconUrl` (which should just be named `icon` then)?

**Comment by paulcbetts** [comment]
If you use a local .ico file, it'll only work on your computer - the Squirrel installer downloads the icon for the uninstaller on-install. This isn't ideal, but it's how it works right now

**Comment by d9k** [comment]
> If you use a local .ico file, it'll only work on your computer 
So why can't icon be distributed with application package?

**Comment by paulcbetts** [comment]
Because IconURL is a URL, and if you specify things that _aren't_ URLs, NuGet will blow up. I suppose we could try a `file:` URL but that'd be quite unintuitive for people

**Comment by lipis** [comment]
@paulcbetts anything.. as long as we can assign some sort of icon to local path :)

**Comment by havenchyk** [comment]
Well, it's not possible right now because of nuget limitations. Feel free to open issue agains nuget or squirrel.windows.

**Comment by mor-o** [comment]
can we reopen this? this is still an issue on private networks with no access to the internet
NuGet fixed their issue already long ago: https://github.com/NuGet/Home/issues/352

**Comment by FrahHS** [comment]
> can we reopen this? this is still an issue on private networks with no access to the internet NuGet fixed their issue already long ago: [NuGet/Home#352](https://github.com/NuGet/Home/issues/352)

Same issue on local network
