### ISSUE TITLE
Application's icon disappears after a few autoupdates.

### ISSUE THREAD

**Issue by lipis** [electron/grunt-electron-installer#76]
Does this happens to anyone else? The icon on Desktop and in the Taskbar are appearing correctly after installation, but sometimes after a few updates they are disappearing an showing the empty file icon.

**Comment by Yserz** [comment]
![no-icon](https://cloud.githubusercontent.com/assets/1138344/10908776/7903b5ee-8234-11e5-8e69-43b7899267c3.png)
![no-icon2](https://cloud.githubusercontent.com/assets/1138344/10908796/951b7488-8234-11e5-9b5c-2f1a4bfeba0b.png)

**Comment by paulcbetts** [comment]
This is a notorious Squirrel bug that I've tried to fix over and over :-/  We'll keep trying!

**Comment by lipis** [comment]
one idea could be to store the icon under the application directory and point to that icon instead of the executable that is printing right now. Would that work somehow?

**Comment by lipis** [comment]
So after further investigation, it appears that the Desktop shortcut (should be the one in start menu as well) points to a specific version/directory/executable of the app, instead of pointing maybe to `app.ico` that exists in the root folder. Because otherwise this file should be created every time that there is an update and this is not OK, if user will decide to delete the icon from the Desktop for example.

![screen shot 2015-11-04 at 13 31 43](https://cloud.githubusercontent.com/assets/125676/10938192/7bad4d72-82f8-11e5-8ceb-22be6bbb5d32.png)

So my prediction is that in our next update the icon will change to an empty file since the folder `app-2.0.2468` will be deleted :/

**Comment by lipis** [comment]
@paulcbetts Where should be the right place to raise this issue..?

**Comment by paulcbetts** [comment]
@lipis squirrel/squirrel.windows

**Comment by lipis** [comment]
I think I found out something that is definitely was an issue.. For the single instance changes that I made I was quitting the app too fast and the squirrel-updated related tasks weren't executed..

Overall the link to Atom answers bunch of questions..

**Comment by havenchyk** [comment]
If you still have the issue, create it against squirrel.windows
